---
name: 'Run Pascal script'
description: 'This action runs Pascal script.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  pathToList:
    description: 'Path to the file containing all paths.'
    required: true
outputs:
  result:
    description: 'Result of the output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
